### ISSUE TITLE
No longer able to install add-on

### ISSUE THREAD

**Issue by jamierowan** [blender-to-gmstudio/blender-gms-vtx-buffer#29]
Hey, I'm unable to install the add on to blender.
I'm in 3.2.1
![Blender Preferences 01_12_2022 08_44_45](https://user-images.githubusercontent.com/76178963/205125807-14b84b18-aa55-4ada-ac3b-220b4e30d081.png)

**Comment by bartteunis** [comment]
Hey.

You're right indeed... That's a known issue that I didn't realize wasn't solved in this exporter.
The directory name in the `Source code (zip)` file on the [latest release page](https://github.com/blender-to-gmstudio/blender-gms-vtx-buffer/releases/latest) contains the version number at the end and that doesn't match the name of the exporter defined in the Python file, which causes the install to fail.

I added a new zip file `blender-gms-vtx-buffer-v1.0.9.zip` that should install fine now (tested this in Blender 3.3)

Thanks for letting me know about this!
